name: jagx_os
description: JagX OS — Custom Android launcher and system UI. Licensed under JRILICENSE.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  battery_plus: ^6.0.1
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  installed_apps: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
